// Generated by dia2code
#ifndef STATE__TOKEN__H
#define STATE__TOKEN__H


namespace state {
  class Piece;
}

#include "Piece.hpp"

namespace state {

  /// class Token - 
  class Token : public state::Piece {
    // Attributes
  public:
    int value;
    // Setters and Getters
  };

};

#endif
