# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/stphd/Desktop/ENSEA_3A/catan/plt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/stphd/Desktop/ENSEA_3A/catan/plt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/stphd/Desktop/ENSEA_3A/catan/plt/CMakeFiles /mnt/c/Users/stphd/Desktop/ENSEA_3A/catan/plt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/stphd/Desktop/ENSEA_3A/catan/plt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code-coverage

# Build rule for target.
code-coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code-coverage
.PHONY : code-coverage

# fast build rule for target.
code-coverage/fast:
	$(MAKE) -f CMakeFiles/code-coverage.dir/build.make CMakeFiles/code-coverage.dir/build
.PHONY : code-coverage/fast

#=============================================================================
# Target rules for targets named clean-headers

# Build rule for target.
clean-headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-headers
.PHONY : clean-headers

# fast build rule for target.
clean-headers/fast:
	$(MAKE) -f CMakeFiles/clean-headers.dir/build.make CMakeFiles/clean-headers.dir/build
.PHONY : clean-headers/fast

#=============================================================================
# Target rules for targets named code-coverage-gcov

# Build rule for target.
code-coverage-gcov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code-coverage-gcov
.PHONY : code-coverage-gcov

# fast build rule for target.
code-coverage-gcov/fast:
	$(MAKE) -f CMakeFiles/code-coverage-gcov.dir/build.make CMakeFiles/code-coverage-gcov.dir/build
.PHONY : code-coverage-gcov/fast

#=============================================================================
# Target rules for targets named generate-headers

# Build rule for target.
generate-headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate-headers
.PHONY : generate-headers

# fast build rule for target.
generate-headers/fast:
	$(MAKE) -f CMakeFiles/generate-headers.dir/build.make CMakeFiles/generate-headers.dir/build
.PHONY : generate-headers/fast

#=============================================================================
# Target rules for targets named dia2code

# Build rule for target.
dia2code: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dia2code
.PHONY : dia2code

# fast build rule for target.
dia2code/fast:
	$(MAKE) -f extern/dia2code/CMakeFiles/dia2code.dir/build.make extern/dia2code/CMakeFiles/dia2code.dir/build
.PHONY : dia2code/fast

#=============================================================================
# Target rules for targets named shared_static

# Build rule for target.
shared_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared_static
.PHONY : shared_static

# fast build rule for target.
shared_static/fast:
	$(MAKE) -f src/shared/CMakeFiles/shared_static.dir/build.make src/shared/CMakeFiles/shared_static.dir/build
.PHONY : shared_static/fast

#=============================================================================
# Target rules for targets named generate-header-state

# Build rule for target.
generate-header-state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate-header-state
.PHONY : generate-header-state

# fast build rule for target.
generate-header-state/fast:
	$(MAKE) -f src/shared/CMakeFiles/generate-header-state.dir/build.make src/shared/CMakeFiles/generate-header-state.dir/build
.PHONY : generate-header-state/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f src/client/CMakeFiles/client.dir/build.make src/client/CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named client_static

# Build rule for target.
client_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_static
.PHONY : client_static

# fast build rule for target.
client_static/fast:
	$(MAKE) -f src/client/CMakeFiles/client_static.dir/build.make src/client/CMakeFiles/client_static.dir/build
.PHONY : client_static/fast

#=============================================================================
# Target rules for targets named generate-header-client

# Build rule for target.
generate-header-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate-header-client
.PHONY : generate-header-client

# fast build rule for target.
generate-header-client/fast:
	$(MAKE) -f src/client/CMakeFiles/generate-header-client.dir/build.make src/client/CMakeFiles/generate-header-client.dir/build
.PHONY : generate-header-client/fast

#=============================================================================
# Target rules for targets named rapport-diapdf-state

# Build rule for target.
rapport-diapdf-state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rapport-diapdf-state
.PHONY : rapport-diapdf-state

# fast build rule for target.
rapport-diapdf-state/fast:
	$(MAKE) -f rapport/CMakeFiles/rapport-diapdf-state.dir/build.make rapport/CMakeFiles/rapport-diapdf-state.dir/build
.PHONY : rapport-diapdf-state/fast

#=============================================================================
# Target rules for targets named rapport

# Build rule for target.
rapport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rapport
.PHONY : rapport

# fast build rule for target.
rapport/fast:
	$(MAKE) -f rapport/CMakeFiles/rapport.dir/build.make rapport/CMakeFiles/rapport.dir/build
.PHONY : rapport/fast

#=============================================================================
# Target rules for targets named unittest

# Build rule for target.
unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest
.PHONY : unittest

# fast build rule for target.
unittest/fast:
	$(MAKE) -f test/CMakeFiles/unittest.dir/build.make test/CMakeFiles/unittest.dir/build
.PHONY : unittest/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f test/CMakeFiles/check.dir/build.make test/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named test_GameCards

# Build rule for target.
test_GameCards: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_GameCards
.PHONY : test_GameCards

# fast build rule for target.
test_GameCards/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_GameCards.dir/build.make test/shared/CMakeFiles/test_GameCards.dir/build
.PHONY : test_GameCards/fast

#=============================================================================
# Target rules for targets named test_Map

# Build rule for target.
test_Map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Map
.PHONY : test_Map

# fast build rule for target.
test_Map/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Map.dir/build.make test/shared/CMakeFiles/test_Map.dir/build
.PHONY : test_Map/fast

#=============================================================================
# Target rules for targets named test_Thief

# Build rule for target.
test_Thief: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Thief
.PHONY : test_Thief

# fast build rule for target.
test_Thief/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Thief.dir/build.make test/shared/CMakeFiles/test_Thief.dir/build
.PHONY : test_Thief/fast

#=============================================================================
# Target rules for targets named test_Invention

# Build rule for target.
test_Invention: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Invention
.PHONY : test_Invention

# fast build rule for target.
test_Invention/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Invention.dir/build.make test/shared/CMakeFiles/test_Invention.dir/build
.PHONY : test_Invention/fast

#=============================================================================
# Target rules for targets named test_Road

# Build rule for target.
test_Road: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Road
.PHONY : test_Road

# fast build rule for target.
test_Road/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Road.dir/build.make test/shared/CMakeFiles/test_Road.dir/build
.PHONY : test_Road/fast

#=============================================================================
# Target rules for targets named test_LongestRoad

# Build rule for target.
test_LongestRoad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_LongestRoad
.PHONY : test_LongestRoad

# fast build rule for target.
test_LongestRoad/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_LongestRoad.dir/build.make test/shared/CMakeFiles/test_LongestRoad.dir/build
.PHONY : test_LongestRoad/fast

#=============================================================================
# Target rules for targets named test_Development

# Build rule for target.
test_Development: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Development
.PHONY : test_Development

# fast build rule for target.
test_Development/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Development.dir/build.make test/shared/CMakeFiles/test_Development.dir/build
.PHONY : test_Development/fast

#=============================================================================
# Target rules for targets named test_Card

# Build rule for target.
test_Card: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Card
.PHONY : test_Card

# fast build rule for target.
test_Card/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Card.dir/build.make test/shared/CMakeFiles/test_Card.dir/build
.PHONY : test_Card/fast

#=============================================================================
# Target rules for targets named test_Display

# Build rule for target.
test_Display: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Display
.PHONY : test_Display

# fast build rule for target.
test_Display/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Display.dir/build.make test/shared/CMakeFiles/test_Display.dir/build
.PHONY : test_Display/fast

#=============================================================================
# Target rules for targets named test_Monopoly

# Build rule for target.
test_Monopoly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Monopoly
.PHONY : test_Monopoly

# fast build rule for target.
test_Monopoly/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Monopoly.dir/build.make test/shared/CMakeFiles/test_Monopoly.dir/build
.PHONY : test_Monopoly/fast

#=============================================================================
# Target rules for targets named test_Player

# Build rule for target.
test_Player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Player
.PHONY : test_Player

# fast build rule for target.
test_Player/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Player.dir/build.make test/shared/CMakeFiles/test_Player.dir/build
.PHONY : test_Player/fast

#=============================================================================
# Target rules for targets named test_Progress

# Build rule for target.
test_Progress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Progress
.PHONY : test_Progress

# fast build rule for target.
test_Progress/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Progress.dir/build.make test/shared/CMakeFiles/test_Progress.dir/build
.PHONY : test_Progress/fast

#=============================================================================
# Target rules for targets named test_TileGroundType

# Build rule for target.
test_TileGroundType: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_TileGroundType
.PHONY : test_TileGroundType

# fast build rule for target.
test_TileGroundType/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_TileGroundType.dir/build.make test/shared/CMakeFiles/test_TileGroundType.dir/build
.PHONY : test_TileGroundType/fast

#=============================================================================
# Target rules for targets named test_City

# Build rule for target.
test_City: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_City
.PHONY : test_City

# fast build rule for target.
test_City/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_City.dir/build.make test/shared/CMakeFiles/test_City.dir/build
.PHONY : test_City/fast

#=============================================================================
# Target rules for targets named test_shared_dummy

# Build rule for target.
test_shared_dummy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_shared_dummy
.PHONY : test_shared_dummy

# fast build rule for target.
test_shared_dummy/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_shared_dummy.dir/build.make test/shared/CMakeFiles/test_shared_dummy.dir/build
.PHONY : test_shared_dummy/fast

#=============================================================================
# Target rules for targets named test_Piece

# Build rule for target.
test_Piece: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Piece
.PHONY : test_Piece

# fast build rule for target.
test_Piece/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Piece.dir/build.make test/shared/CMakeFiles/test_Piece.dir/build
.PHONY : test_Piece/fast

#=============================================================================
# Target rules for targets named test_VictoryPoints

# Build rule for target.
test_VictoryPoints: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_VictoryPoints
.PHONY : test_VictoryPoints

# fast build rule for target.
test_VictoryPoints/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_VictoryPoints.dir/build.make test/shared/CMakeFiles/test_VictoryPoints.dir/build
.PHONY : test_VictoryPoints/fast

#=============================================================================
# Target rules for targets named test_Resource

# Build rule for target.
test_Resource: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Resource
.PHONY : test_Resource

# fast build rule for target.
test_Resource/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Resource.dir/build.make test/shared/CMakeFiles/test_Resource.dir/build
.PHONY : test_Resource/fast

#=============================================================================
# Target rules for targets named test_LargestArmy

# Build rule for target.
test_LargestArmy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_LargestArmy
.PHONY : test_LargestArmy

# fast build rule for target.
test_LargestArmy/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_LargestArmy.dir/build.make test/shared/CMakeFiles/test_LargestArmy.dir/build
.PHONY : test_LargestArmy/fast

#=============================================================================
# Target rules for targets named test_RoadConstruction

# Build rule for target.
test_RoadConstruction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_RoadConstruction
.PHONY : test_RoadConstruction

# fast build rule for target.
test_RoadConstruction/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_RoadConstruction.dir/build.make test/shared/CMakeFiles/test_RoadConstruction.dir/build
.PHONY : test_RoadConstruction/fast

#=============================================================================
# Target rules for targets named test_Special

# Build rule for target.
test_Special: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Special
.PHONY : test_Special

# fast build rule for target.
test_Special/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Special.dir/build.make test/shared/CMakeFiles/test_Special.dir/build
.PHONY : test_Special/fast

#=============================================================================
# Target rules for targets named test_Game

# Build rule for target.
test_Game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Game
.PHONY : test_Game

# fast build rule for target.
test_Game/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Game.dir/build.make test/shared/CMakeFiles/test_Game.dir/build
.PHONY : test_Game/fast

#=============================================================================
# Target rules for targets named test_Tile

# Build rule for target.
test_Tile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Tile
.PHONY : test_Tile

# fast build rule for target.
test_Tile/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Tile.dir/build.make test/shared/CMakeFiles/test_Tile.dir/build
.PHONY : test_Tile/fast

#=============================================================================
# Target rules for targets named test_TileGround

# Build rule for target.
test_TileGround: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_TileGround
.PHONY : test_TileGround

# fast build rule for target.
test_TileGround/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_TileGround.dir/build.make test/shared/CMakeFiles/test_TileGround.dir/build
.PHONY : test_TileGround/fast

#=============================================================================
# Target rules for targets named test_Token

# Build rule for target.
test_Token: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Token
.PHONY : test_Token

# fast build rule for target.
test_Token/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Token.dir/build.make test/shared/CMakeFiles/test_Token.dir/build
.PHONY : test_Token/fast

#=============================================================================
# Target rules for targets named test_TileBeach

# Build rule for target.
test_TileBeach: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_TileBeach
.PHONY : test_TileBeach

# fast build rule for target.
test_TileBeach/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_TileBeach.dir/build.make test/shared/CMakeFiles/test_TileBeach.dir/build
.PHONY : test_TileBeach/fast

#=============================================================================
# Target rules for targets named test_Knight

# Build rule for target.
test_Knight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_Knight
.PHONY : test_Knight

# fast build rule for target.
test_Knight/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_Knight.dir/build.make test/shared/CMakeFiles/test_Knight.dir/build
.PHONY : test_Knight/fast

#=============================================================================
# Target rules for targets named test_TileBeachType

# Build rule for target.
test_TileBeachType: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_TileBeachType
.PHONY : test_TileBeachType

# fast build rule for target.
test_TileBeachType/fast:
	$(MAKE) -f test/shared/CMakeFiles/test_TileBeachType.dir/build.make test/shared/CMakeFiles/test_TileBeachType.dir/build
.PHONY : test_TileBeachType/fast

#=============================================================================
# Target rules for targets named test_client_dummy

# Build rule for target.
test_client_dummy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_client_dummy
.PHONY : test_client_dummy

# fast build rule for target.
test_client_dummy/fast:
	$(MAKE) -f test/client/CMakeFiles/test_client_dummy.dir/build.make test/client/CMakeFiles/test_client_dummy.dir/build
.PHONY : test_client_dummy/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... code-coverage"
	@echo "... clean-headers"
	@echo "... rebuild_cache"
	@echo "... code-coverage-gcov"
	@echo "... generate-headers"
	@echo "... dia2code"
	@echo "... shared_static"
	@echo "... generate-header-state"
	@echo "... client"
	@echo "... client_static"
	@echo "... generate-header-client"
	@echo "... rapport-diapdf-state"
	@echo "... rapport"
	@echo "... unittest"
	@echo "... check"
	@echo "... test_GameCards"
	@echo "... test_Map"
	@echo "... test_Thief"
	@echo "... test_Invention"
	@echo "... test_Road"
	@echo "... test_LongestRoad"
	@echo "... test_Development"
	@echo "... test_Card"
	@echo "... test_Display"
	@echo "... test_Monopoly"
	@echo "... test_Player"
	@echo "... test_Progress"
	@echo "... test_TileGroundType"
	@echo "... test_City"
	@echo "... test_shared_dummy"
	@echo "... test_Piece"
	@echo "... test_VictoryPoints"
	@echo "... test_Resource"
	@echo "... test_LargestArmy"
	@echo "... test_RoadConstruction"
	@echo "... test_Special"
	@echo "... test_Game"
	@echo "... test_Tile"
	@echo "... test_TileGround"
	@echo "... test_Token"
	@echo "... test_TileBeach"
	@echo "... test_Knight"
	@echo "... test_TileBeachType"
	@echo "... test_client_dummy"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

